#!/bin/bash
echo "=== Vercel Migration Guide ==="
echo ""
echo "Option 1: Via Vercel CLI (Recommended)"
echo "1. vercel login"
echo "2. vercel link"
echo "3. vercel env pull .env.local"
echo "4. npx prisma migrate deploy"
echo ""
echo "Option 2: Direct with connection string"
echo "1. Get AIBO_DB_PRISMA_DATABASE_URL from Vercel dashboard"
echo "2. export AIBO_DB_PRISMA_DATABASE_URL='your-connection-string'"
echo "3. npx prisma migrate deploy"
echo ""
